-- https://github.com/benfrain/neovim/blob/ea13388ddf71e7107be3bec8c1cdcc60ceff7223/lua/mappings.lua
vim.keymap.set("n", "<leader>zf", require("fzf-lua").files, { desc = "FZF Files" })
vim.keymap.set("n", "<leader><leader>", require("fzf-lua").resume, { desc = "FZF Resume" })
-- vim.keymap.set("n", "<leader>zr", require("fzf-lua").registers, { desc = "Registers" })
-- vim.keymap.set("n", "<leader>zm", require("fzf-lua").marks, { desc = "Marks" })
-- vim.keymap.set("n", "<leader>zk", require("fzf-lua").keymaps, { desc = "Keymaps" })
-- vim.keymap.set("n", "<leader>zg", require("fzf-lua").live_grep, { desc = "FZF Grep" })
-- vim.keymap.set("n", "<leader>zb", require("fzf-lua").buffers, { desc = "FZF Buffers" })
-- vim.keymap.set("v", "<leader>z8", require("fzf-lua").grep_visual, { desc = "FZF Selection" })
-- vim.keymap.set("n", "<leader>z7", require("fzf-lua").grep_cword, { desc = "FZF Word" })
-- vim.keymap.set("n", "<leader>zt", require("fzf-lua").helptags, { desc = "Help Tags" })
-- vim.keymap.set("n", "<leader>zgc", require("fzf-lua").git_bcommits, { desc = "Browse File Commits" })
-- vim.keymap.set("n", "<leader>zgs", require("fzf-lua").git_status, { desc = "Git Status" })
-- vim.keymap.set("n", "<leader>zs", require("fzf-lua").spell_suggest, { desc = "Spelling Suggestions" })
-- vim.keymap.set("n", "<leader>zl", require("fzf-lua").lsp_definitions, { desc = "Jump to Definition" })
