require("config.lazy")
require("config.sets")
require("config.lsp")
-- Seems like some things have to be done as config and not as plugins.
require("config.lualine")
require("config.yankstack")
require("config.keymaps")
require("config.user-functions")
require("config.telescope.keymaps")
require("config.nerdtree.keymaps")
require("config.undotree.keymaps")
require("config.fzf.keymaps")
