return {
  "folke/neodev.nvim",
  {"catppuccin/nvim", name = "catppuccin", priority = 1000},
  "nvim-telescope/telescope.nvim",
  "mbbill/undotree",
  "ellisonleao/gruvbox.nvim",
  "williamboman/mason.nvim",
  "williamboman/mason-lspconfig.nvim",
  "neovim/nvim-lspconfig",
  "preservim/nerdtree",
  "tpope/vim-fugitive",
  "tpope/vim-commentary",
  {"nvim-treesitter/nvim-treesitter", build= ":TSUpdate"},
  "folke/which-key.nvim",
  {"nvim-lualine/lualine.nvim", dependencies = {'nvim-tree/nvim-web-devicons'}},
  'akinsho/bufferline.nvim',
  'maxbrunsfeld/vim-yankstack',
  {"folke/neoconf.nvim", cmd = "Neoconf"},
}
