return {
  -- "folke/neodev.nvim",
  --{"catppuccin/nvim", name = "catppuccin", priority = 1000},
  "nvim-telescope/telescope.nvim",
  "mbbill/undotree",
  "williamboman/mason.nvim",
  "williamboman/mason-lspconfig.nvim",
  "neovim/nvim-lspconfig",
  {"L3MON4D3/LuaSnip", dependencies = {"rafamadriz/friendly-snippets"}, tag = "v2.3.0", build = "make install_jsregexp"},
  "rafamadriz/friendly-snippets",
  "preservim/nerdtree",
  "tpope/vim-fugitive",
  "tpope/vim-commentary",
  {"nvim-treesitter/nvim-treesitter", build= ":TSUpdate"},
  "folke/which-key.nvim",
  {"nvim-lualine/lualine.nvim", dependencies = {"nvim-tree/nvim-web-devicons"}},
  "akinsho/bufferline.nvim",
  "maxbrunsfeld/vim-yankstack",
  "mhinz/vim-signify",
  "farmergreg/vim-lastplace",
  "hrsh7th/nvim-cmp",
  "hrsh7th/cmp-buffer",
  "hrsh7th/cmp-path",
  "hrsh7th/cmp-nvim-lua",
  "hrsh7th/cmp-nvim-lsp",
  "hrsh7th/cmp-cmdline",
  "hrsh7th/cmp-nvim-lsp-signature-help",
  "onsails/lspkind-nvim",
  "nvim-lua/lsp_extensions.nvim",
  "saadparwaiz1/cmp_luasnip",
  "simrat39/rust-tools.nvim",
  "ibhagwan/fzf-lua",
  "junegunn/gv.vim",
}
